### ISSUE TITLE
Have you thought about passing variables?

### ISSUE THREAD

**Issue by idkjs** [drejohnson/with-reason-apollo#3]
Once you render your list, you might click a list item, then go to your home route, pass the variable to the single item query
```
let query =
  [@bs]
  gql(
    {|
    query episode {
      episode: Episode (id: "cixm6eovajibk0180k40rcoja") { // pass variable here
        id
        title
      }
    }
  |}
  );
```
 then render that data? @Gregoirevda

**Comment by drejohnson** [comment]
This is how you structure the query to pass variable

```
let query =
  [@bs]
  gql(
    {|
    query episode($id: ID) {
      episode: Episode (id: $id) { 
        id
        title
      }
    }
  |}
  );
```

**Comment by idkjs** [comment]
Sure. I guess i'm more thinking about getting the variable from the current/clicked episodeitem and passing it to the next module. Like we would do in react-router. So conceptually, store the value of the current id, pass it to props.params.id, then pass that to the ID variable in a query. So maybe make a variable type, set it to something then pass it to config? Thinking out loud, looking at the react-router bindings.

**Comment by drejohnson** [comment]
Yeah, I think this will be tricky. You'll need a way to access param prop from react-router bindings and from what I can see, you can't pass a variable into the graphql query. In js, you would use the graphql hoc to pass variable but not sure how to access the ID variable from query.
```
graphql(query, {
  options: params => ({
    variables: {
      id: params.id,
    },
  }),
})
```

**Comment by drejohnson** [comment]
There needs to be a way to set variables from reason-apollo. That way it can be passed to the query

**Comment by Gregoirevda** [comment]
@idkjs @drejohnson 
Just added the feature to add query variables in reason-apollo v0.4.0. (Just published on npm)
I show how to pass variables in the upgraded repo: https://github.com/Gregoirevda/reason-apollo-test-usage using the new version of reason-apollo

**Comment by drejohnson** [comment]
@Gregoirevda passing a variable works great but not passing one doesn't render the query.

**Comment by Gregoirevda** [comment]
@drejohnson I realized it after pushing... It's fixed now. The example usage repository shows it too now. You can find same explanation here: https://github.com/Gregoirevda/reason-apollo/issues/4

**Comment by drejohnson** [comment]
@Gregoirevda Awesome, thanks!
@idkjs I added example of using react-router's match.param prop for the query variable.

**Comment by idkjs** [comment]
You are a bad ass, man. So the FetchEpisode set to Apollo.Client(Config). Config takes to varialbes. So when you call FetchEpisode you can pass it query and variables you are passing that in addition to "Config" because Apollo.Client takes more than what we are passing it in Config. That was super not clear to me. Its like hidden variables. I guess you have to know the package. How did you come to understand that is how it worked being that you are new to reason as well?
